language: ruby
rvm:
- 2.5.1
cache: bundler
before_install:
- export GEM_HOME=$PWD/vendor/bundle/ruby/2.3.1
- gem install -v 2.0.1 bundler
script:
- gem install net-http-pipeline -v 1.0.1
- RAILS_ENV=test bundle exec rake db:create db:migrate
- chmod u+x bin/rails
- bin/rails test test/controllers/class_standing_controller_test.rb
- bundle exec cucumber
